# Generated by Django 5.2.14 on 2026-05-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCausadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('gerou_queimada', models.BooleanField(verbose_name='Gerou Queimada')),
            ],
            options={
                'verbose_name': 'Ação Causadora',
                'verbose_name_plural': 'Ações Causadoras',
            },
        ),
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_feita', models.CharField(max_length=100, verbose_name='Ação Feita')),
                ('data', models.DateField(verbose_name='Data')),
                ('organizacao', models.CharField(max_length=100, verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='ClimaTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('influencia', models.CharField(max_length=100, verbose_name='Influência')),
                ('tempo', models.CharField(max_length=100, verbose_name='Tempo')),
            ],
            options={
                'verbose_name': 'Clima Tempo',
                'verbose_name_plural': 'Climas Tempo',
            },
        ),
        migrations.CreateModel(
            name='DadosSatelites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satelite', models.CharField(max_length=100, verbose_name='Satélite')),
                ('dados_fornecidos', models.TextField(verbose_name='Dados Fornecidos')),
            ],
            options={
                'verbose_name': 'Dados Satélite',
                'verbose_name_plural': 'Dados Satélites',
            },
        ),
        migrations.CreateModel(
            name='EspeciesRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100, verbose_name='Espécie')),
                ('quantia', models.IntegerField(verbose_name='Quantia')),
            ],
            options={
                'verbose_name': 'Espécie em Risco',
                'verbose_name_plural': 'Espécies em Risco',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('coordenada', models.CharField(max_length=100, verbose_name='Coordenada')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Severidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(max_length=50, verbose_name='Grau')),
            ],
            options={
                'verbose_name': 'Severidade',
                'verbose_name_plural': 'Severidades',
            },
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=100, verbose_name='Classificação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('especies_risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especiesrisco')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='Biodiversidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da biodiversidade')),
                ('dados_satelites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dadossatelites')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
                ('severidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.severidade')),
            ],
            options={
                'verbose_name': 'Biodiversidade',
                'verbose_name_plural': 'Biodiversidades',
            },
        ),
        migrations.CreateModel(
            name='PerdaHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_total_danificada', models.FloatField(verbose_name='Área Total Danificada')),
                ('quant_especies_prejudicadas', models.IntegerField(verbose_name='Quantidade Espécies Prejudicadas')),
                ('biodiversidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.biodiversidade')),
            ],
            options={
                'verbose_name': 'Perda Habitat',
                'verbose_name_plural': 'Perdas Habitat',
            },
        ),
        migrations.CreateModel(
            name='PoliciaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
            ],
            options={
                'verbose_name': 'Polícia Ambiental',
                'verbose_name_plural': 'Polícias Ambientais',
            },
        ),
        migrations.CreateModel(
            name='Queimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_km', models.FloatField(verbose_name='Área KM')),
                ('duracao', models.IntegerField(verbose_name='Duração')),
                ('data', models.DateField(verbose_name='Data')),
                ('acao_causadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acaocausadora')),
                ('dados_satelites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dadossatelites')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
                ('perda_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perdahabitat')),
                ('severidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.severidade')),
            ],
            options={
                'verbose_name': 'Queimada',
                'verbose_name_plural': 'Queimadas',
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantia', models.FloatField(verbose_name='Quantia')),
                ('data', models.DateField(verbose_name='Data')),
                ('queimadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.queimada')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policiaambiental')),
                ('queimada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.queimada')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cidade')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
                ('queimadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.queimada')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pesquisador', models.CharField(max_length=100, verbose_name='Nome Pesquisador')),
                ('pesquisa', models.TextField(verbose_name='Pesquisa')),
                ('data', models.DateField(verbose_name='Data')),
                ('dados_satelites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dadossatelites')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.AddField(
            model_name='especiesrisco',
            name='severidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.severidade'),
        ),
    ]
