# Generated by Django 5.2.12 on 2026-03-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='Livro',
            new_name='livro',
        ),
    ]
